root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
ignorePatterns:
  - dist
  - eslintrc.yml
  - node_modules

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - react-refresh
rules:
  indent:
    - error
    - 2
  # linebreak-style:
  #   - error
  #   - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  
  react-refresh/only-export-components:
    - warn
    - allowConstantExport: true
