root: true
env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended-type-checked # or plugin:@typescript-eslint/strict-type-checked
  # - plugin:@typescript-eslint/stylistic-type-checked # TODO: Re-enable later, causes eslint(prefer-nullish-coalescing) error in vite.config.ts
  - plugin:react/recommended
  - plugin:react/jsx-runtime # After React v17+, no need to import React from 'react' everywhere.
  - plugin:react-hooks/recommended
  - prettier # eslint-config-prettier (put it last to override other configs)
globals:
  __dirname: true
ignorePatterns:
  - dist
  - node_modules

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
    - ./tsconfig.node.json
  # tsconfigRootDir: ./
plugins:
  - '@typescript-eslint'
  - react
  - react-refresh

settings:
  # Fix the "Warning: React version not specified in eslint-plugin-react settings" message.
  react:
    version: detect

  # import/extensions:
  #   - .ts
  #   - .tsx
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  # Absolute paths
  import/resolver: # eslint-import-resolver-***
    # https://github.com/import-js/eslint-plugin-import/issues/1485#issuecomment-535351922
    typescript: {}
    alias:
      extensions:
        - .ts
        - .tsx
      map:
        # Path aliases for imports (alphabetical order)
        #* Mirror changes in vite.config.ts, tsconfig.json
        - ['@', './src']
        - ['@assets', './src/assets']
        - ['@components', './src/components']
        - ['@pages', './src/pages']
        - ['@routes', './src/routes']

rules:
  ###########
  # General #
  ###########

  no-console:
    - error

  curly:
    - error
    - all
  # quotes:
  #   - error
  #   - single

  #################
  # React Refresh #
  #################

  react-refresh/only-export-components:
    - warn
    - allowConstantExport: true
