printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true # default: false
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always
requirePragma: false
insertPragma: false
endOfLine: lf
singleAttributePerLine: false
